### ISSUE TITLE
Impermanence

### ISSUE THREAD

**Issue by tbaumann** [nakato/nixos-sbc#18]
I can see that there are some code comments in the btrfs-subvol code mentioning putting the rootfs into ram.

What's the purpose of `/NIXOS_RAMIFY`?

```nix
  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "size=3G" "mode=755" ]; # mode=755 so only root can write to those files
    };
```

conflicts with the definition in the sbc module. Just in case you have done this before, perhaps you can share...

Also, if nixos supports tempfs as root, how does  this even fit in with all the bootstrap commands? Because a tempfs will be empty. I mean like the nix index via `/nix-path-registration `

**Comment by tbaumann** [comment]
I found breadcrumbs.

[/nix/store/nix-path-registration](https://github.com/NixOS/nixpkgs/blob/b6cf41ad8dfcc5a1e62a9b8bae3ef8e556f560bb/nixos/modules/installer/netboot/netboot.nix#L139)

They just do it every boot. And the index is not in `/` but rather in the nix store location.

**Comment by tbaumann** [comment]
There is no special handling of root on tempfs either in nixpkgs nor the impermanence module

**Comment by nakato** [comment]
The rootfs is made with `mkfs.btrfs`, so subvolumes cannot be created, so RAMIFY's job is to make the subvolumes and move things into place.

I boot one of my boards with impermanence, this is the fs config I use for it.

```
  fileSystems = { 
    "/" = with lib; {
      device = mkForce "none";
      fsType = mkForce "tmpfs";
      options = mkForce [ "size=8G" "mode=755" ];
    };  
    "/persistent" = { 
      device = config.fileSystems."/nix".device;
      fsType = "btrfs";
      options = [ "subvol=@persistent" "compress=zstd" ];
      neededForBoot = true;
    };  
    "/swap" = { 
      device = config.fileSystems."/nix".device;
      fsType = "btrfs";
      options = [ "subvol=@swap" "compress=zstd" ];
      neededForBoot = true;
    };  
    "/tmp" = with lib; {
      device = "none";
      fsType = mkForce "tmpfs";
      options = mkForce [ "size=32G" ];
    };  
  }; 
```

You'll need to boot with root once to be able to make these new subvols by hand (`@persistent` and `@swap`) and then apply the tmpfs root, or you could mount the SD card on the computer and create them ahead of time.

I'm heading out for the day right now, so I can't go into more detail right now, but feel free to add additional questions about this here in the meantime.

**Comment by tbaumann** [comment]
Got it. Looks like I maybe need two nixosSystems entries. One for the sd image and one for follow-up updates with all the right file systems

**Comment by nakato** [comment]
> I found breadcrumbs.
> 
> [/nix/store/nix-path-registration](https://github.com/NixOS/nixpkgs/blob/b6cf41ad8dfcc5a1e62a9b8bae3ef8e556f560bb/nixos/modules/installer/netboot/netboot.nix#L139)
> 
> They just do it every boot. And the index is not in `/` but rather in the nix store location.

nix-path-registration is first-boot only as it's all in /nix.  `/etc` gets populated by one of the scripts initrd calls, in stage-2 I think.

**Comment by nakato** [comment]
> Got it. Looks like I maybe need two nixosSystems entries. One for the sd image and one for follow-up updates with all the right file systems

It would be worthwhile to extend the handling to support other, user-defined partitions so special handling isn't required.  I'd like to be able do impermanence from first-boot as well.

I can think of a couple of ways of handling the config.filesystem part, so I'll write up a dedicated issue for that soon to put it on the todo list.

I chose to not change the path that nixpkgs places *nix-path-registration* bits at, which for physical disks is `/nix-path-registration`, that'll have to change.  It's a first-boot thing, so it's not a breaking change to update, which is good.

**Comment by tbaumann** [comment]
FYI.

mkfs.brtrfs supports `-u|--subvol <subdir>:<flags>` to turn subdirectories into subvolumes.

But `nixos/lib/make-btrfs-fs.nix` doesn't. :D

**Comment by nakato** [comment]
> FYI.
> 
> mkfs.brtrfs supports `-u|--subvol <subdir>:<flags>` to turn subdirectories into subvolumes.

Oh, that's the way forward then; moving the files around on first-boot is tricky with it being pre-resize, so I'm all for that going away.

Looks like this feature has not hit a tagged btrfs-progs release yet, and will be in v6.11.

Looks like v6.12 will include a `--compression` flag too!

**Comment by nakato** [comment]
I probably won't wait for the btrfs-progs 6.11 to drop before merging the code in PR20.

I need to give it a few more tests to make sure it works as expected.  I forgot to update the resize on my first test of it, but otherwise I was able to provision directly to impermanence with it.

Being able to use --subvol with mkfs.btrfs is so much better than what had to be done on first-boot before that was an option.

**Comment by nakato** [comment]
#20 has been merged.

**Comment by nakato** [comment]
I've added a quick document, e8ab7f065cfa07856af6ad6437a827eaab1ba5ba, on how to setup impermanence as it currently is only documented in one of these github PR's/Issues.  As I believe PR 20 and the followup fix to stop using unshare have direct-to-impermanence working (I've provisioned with it), I think this issue can be closed.  If this is still an issue, feel free to re-open.
