### ISSUE TITLE
missing netfilter modules required for default firewall rules on bpi-r4

### ISSUE THREAD

**Issue by DirectXMan12** [nakato/nixos-sbc#34]
looks like the default kernel rules on nixos use the netfilter pkttype match (see the `input` chain, looks like it's used for controlling refused packet logging) extension (enabled by `CONFIG_NETFILTER_XT_MATCH_PKTTYPE` afaict), which doesn't get included when the bpi-r4 kernel.

i *think* this is because we don't turn on `autoModules`, and nothing specifies it manually.

considering a significant intended usecase of these is as routers, i think it'd be a good idea to turn on most/all of the netfilter options as modules at least, especially since it makes the default firewall rules work.

**Comment by DirectXMan12** [comment]
alternatively, a way to turn back on `autoModules` and just force-off the bigger stuff would be nice, i think -- there's a lot of networking options, it'd be nice not to have to manually toggle all of them.

**Comment by nakato** [comment]
autoModules just doesn't work, it enables too much, and it means circular dependencies that can't be disabled.  I don't have the resources for a big build box to support this.

I really need to make a generic extraStructuredConfig for this, as it's been done to the R3, and copying the big chunk of settings is not great, but I'll do that for now.
