### ISSUE TITLE
bpir3 pcieFixup doesn't seem to work

### ISSUE THREAD

**Issue by ghostbuster91** [nakato/nixos-sbc#9]
The `pcieFixup` is [turned on by default](https://github.com/nakato/nixos-sbc/blob/cfb3e99bc9270c3d0a997532725f6aa7e9445190/modules/boards/bananapi/bpir3/default.nix#L18). 

The implementation of the workaround is the same as it used to be with older kernels. However, it seems that it doesn't work anymore. When I try to configure nvme device I am getting:
```
<<< NixOS Stage 1 >>>



loading module rfkill...

loading module cfg80211...

loading module mt7915e...

loading module mii...

running udev...

Starting systemd-udevd version 255.6

kbd_mode: KDSKBMODE: Inappropriate ioctl for device

Gstarting device mapper and LVM...

checking /dev/disk/by-uuid/0b5e3376-c7e9-4284-9514-9c3b51244f19...

fsck (busybox 1.36.1)

[fsck.ext4 (1) -- /mnt-root/] fsck.ext4 -a /dev/disk/by-uuid/0b5e3376-c7e9-4284-9514-9c3b51244f19

root: recovering journal

root: clean, 278458/7449072 files, 1519866/30558075 blocks

mounting /dev/disk/by-uuid/0b5e3376-c7e9-4284-9514-9c3b51244f19 on /...

waiting for device /dev/disk/by-partlabel/disk-nvme0n1-var to appear.......................

Timed out waiting for device /dev/disk/by-partlabel/disk-nvme0n1-var, trying to mount anyway.

mounting /dev/disk/by-partlabel/disk-nvme0n1-var on /var...

[   36.127976] /dev/disk/by-partlabel/disk-nvme0n1-var: Can't lookup blockdev

mount: mounting /dev/disk/by-partlabel/disk-nvme0n1-var on /mnt-root/var failed: No such file or directory



An error occurred in stage 1 of the boot process, which must mount the

root filesystem on `/mnt-root' and then start stage 2.  Press one

of the following keys:



  r) to reboot immediately

  *) to ignore the error and continue
```

Ignoring the error actually correctly boots the system with the nvme partitions mounted. The problem is that the boot process halts until user makes the choice.

**Comment by nakato** [comment]
```
1.040656: mtk-pcie-gen3 host bridge appears
( 0000:01:00.0 shows up here on warm boot)
1.466971: Stage-1-init begins
?.??????: pci device 0000:01:00.0 shows up
6.245330: "starting device mapper and LVM..."
12.613806: stage-2 starts
20.446846: nvme nvme0: pci function 0000:01:00.0
20.446879: nvme 0000:01:00.0: enabling device (0000 -> 0002)
```

Indeed, NVMe is showing up quite late.

I don't see any changes in the mediatek pcie3 driver, and the script didn't drop an "INFO" line at X.XXXXXX stating that the bridge was missing, so it either exists and ran, or the PCIe device already existed.

I think the issue is probably a missing kernel module, seeing as in my case it showed up in stage-2.

> Ignoring the error actually correctly boots the system with the nvme partitions mounted.

I'll bet, when you hit `*` to ignore and continue, when stage-2 hits and systemd fires up, systemd ends up taking care of the mounting as part of local-fs.target.

I've added the `nvme` module to `boot.initrd.availableKernelModules` in cf0957c2e7b1b19ce5b60ecd3b1c213547159c6b, and now I can see NVMe loading up before the stage-1 LVM scan, which is where it should show up, so this should fix the issue.

```
1.038817: mtk-pcie-gen3 host bridge appears
1.567623: Stage-1-init begins
5.823912: pci device 0000:01:00.0 shows up
6.083566: NVMe device apepars
10.551519: "starting device mapper and LVM..."
12.778144: stage-2 starts
```

**Comment by ghostbuster91** [comment]
> I'll bet, when you hit * to ignore and continue, when stage-2 hits and systemd fires up, systemd ends up taking care of the mounting as part of local-fs.target.

I cannot say for sure that this is what is happening but indeed after ignoring the error the system booted properly. So, I guess that your bet is correct.

> I think the issue is probably a missing kernel module, seeing as in my case it showed up in stage-2.

Now, once you said it, I vaguely remember you telling me similar thing in the previous repository about the nvme support. I, then, added it to my configuration and forgot about it. 

> I've added the nvme module to boot.initrd.availableKernelModules in https://github.com/nakato/nixos-sbc/commit/cf0957c2e7b1b19ce5b60ecd3b1c213547159c6b, and now I can see NVMe loading up before the stage-1 LVM scan, which is where it should show up, so this should fix the issue.

Awesome, thank you and sorry for the long delay.
